### ISSUE TITLE
Generator fails when browserslist >= 4.8.4 installed

### ISSUE THREAD

**Issue by outoftime** [robinweser/inline-style-prefixer#191]
[Reduction](https://repl.it/repls/DefiantOpaqueEmulation)

---

When invoking `generateData()` with browserslist 4.8.4 or newer installed, the following error obtains:

```
TypeError: Cannot read property 'x' of undefined
    at generatePrefixMap (/home/runner/DefiantOpaqueEmulation/node_modules/inline-style-prefixer/lib/generator/generatePrefixMap.js:54:31)
    at generateData (/home/runner/DefiantOpaqueEmulation/node_modules/inline-style-prefixer/lib/generator/index.js:74:71)
    at /home/runner/DefiantOpaqueEmulation/index.js:6:30    at Script.runInContext (vm.js:133:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

I believe this is because `ie_mob` is hard-coded into the [`prefixBrowserMap`](https://github.com/robinweser/inline-style-prefixer/blob/211edd82854a9dbc97db179ade277c43f3f5a710/modules/generator/generatePrefixMap.js#L18) but as of browserslist 4.8.4 it is no longer returned by queries, presumably because it was marked as a dead browser in [this commit](https://github.com/browserslist/browserslist/commit/61e7c94a887fbd739c304f7ad2d7ba06bbba017e).

As a workaround, downgrading to browserslist 4.8.3 fixes the error.

**Comment by robinweser** [comment]
Would you be willing to send a PR that removes ie_mob? I believe it mostly mirrors IE anyways and given its usage it is kinda dead for sure.
